# Generated by Django 5.0.3 on 2024-04-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trekmate', '0002_alter_post_author_post_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
