# Generated by Django 5.0.3 on 2024-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trekmate', '0004_alter_itinerary_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='id',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='i_id',
            field=models.CharField(default=2, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
