# Generated by Django 5.0.3 on 2024-04-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trekmate', '0005_remove_itinerary_id_itinerary_i_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
            ],
        ),
    ]
