# Generated by Django 5.0.3 on 2024-04-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trekmate', '0007_remove_gear_category_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
    ]
