# Generated by Django 5.0.3 on 2024-04-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trekmate', '0008_remove_shippingaddress_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
