# Generated by Django 5.0.3 on 2024-04-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trekmate', '0010_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='cost',
            field=models.CharField(default='', max_length=50),
        ),
    ]
