# Generated by Django 5.0.3 on 2024-04-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trekmate', '0011_itinerary_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='difficulty',
            field=models.CharField(default='Moderate', max_length=100),
            preserve_default=False,
        ),
    ]
